name: cryptography

services:
  postgres:
    image: 'postgres'
    container_name: 'postgres_cryptography'
    environment:
      - 'POSTGRES_DB=postgres_cryptography'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  rabbitmq:
    image: 'rabbitmq'
    container_name: 'rabbitmq_cryptography'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'cryptography_server'
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres_cryptography'
      - 'SPRING_RABBITMQ_HOST=rabbitmq'
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
